In [25]:
import pandas as pd

df_train = pd.read_csv('/content/drug_review_train.csv.zip')
df_train['polarity'] = df_train['rating'].apply(lambda x: 0 if x <= 5 else 1)
display(df_train.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,89879,Cyclosporine,keratoconjunctivitis sicca,"""i have used restasis for about a year now and...",2.0,"April 20, 2013",69,147,0
1,1,143975,Etonogestrel,birth control,"""my experience has been somewhat mixed. i have...",7.0,"August 7, 2016",4,136,1
2,2,106473,Implanon,birth control,"""this is my second implanon would not recommen...",1.0,"May 11, 2016",6,140,0
3,3,184526,Hydroxyzine,anxiety,"""i recommend taking as prescribed, and the bot...",10.0,"March 19, 2012",124,104,1
4,4,91587,Dalfampridine,multiple sclerosis,"""i have been on ampyra for 5 days and have bee...",9.0,"August 1, 2010",101,74,1

In [26]:
df_test = pd.read_csv('/content/drug_review_test.csv.zip')
df_test['polarity'] = df_test['rating'].apply(lambda x: 0 if x <= 5 else 1)
display(df_test.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,163740,Mirtazapine,depression,"""i've tried a few antidepressants over the yea...",10.0,"February 28, 2012",22,68,1
1,1,206473,Mesalamine,"crohn's disease, maintenance","""my son has crohn's disease and has done very ...",8.0,"May 17, 2009",17,48,1
2,2,39293,Contrave,weight loss,"""contrave combines drugs that were used for al...",9.0,"March 5, 2017",35,143,1
3,3,97768,Cyclafem 1 / 35,birth control,"""i have been on this birth control for one cyc...",9.0,"October 22, 2015",4,149,1
4,4,208087,Zyclara,keratosis,"""4 days in on first 2 weeks. using on arms an...",4.0,"July 3, 2014",13,60,0

In [27]:
df_validation = pd.read_csv('/content/drug_review_validation.csv.zip')
df_validation['polarity'] = df_validation['rating'].apply(lambda x: 0 if x <= 5 else 1)
display(df_validation.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,191114,Campral,alcohol dependence,"""sober a year 8-25-11. god, aa and campral hav...",10.0,"September 3, 2011",33,41,1
1,1,142693,Levonorgestrel,birth control,"""i've been on birth control for a while now du...",4.0,"August 9, 2017",3,140,0
2,2,71561,Vraylar,bipolar disorde,"""hi, this is an updated experience. \r\r\n\r\r...",8.0,"August 16, 2016",12,131,1
3,3,25765,Ethinyl estradiol / norelgestromin,birth control,"""i have been on the ortho evra patch for just ...",8.0,"September 15, 2013",16,138,1
4,4,12843,Etanercept,psoriasis,"""i have been on enbrel for 7 years and i have ...",9.0,"August 5, 2010",9,65,1

## Cleaning Text Data

### Subtask:
Cleaning the 'review' column in `df_train`, `df_test`, and `df_validation` by removing HTML tags, special characters, and numbers.

In [28]:
import re

def clean_text(text):
    if not isinstance(text, str):
        return text
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove special characters and numbers, keep only alphabetic characters and spaces
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

df_train['review'] = df_train['review'].apply(clean_text)
df_test['review'] = df_test['review'].apply(clean_text)
df_validation['review'] = df_validation['review'].apply(clean_text)

display(df_train.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,89879,Cyclosporine,keratoconjunctivitis sicca,i have used restasis for about a year now and ...,2.0,"April 20, 2013",69,147,0
1,1,143975,Etonogestrel,birth control,my experience has been somewhat mixed i have b...,7.0,"August 7, 2016",4,136,1
2,2,106473,Implanon,birth control,this is my second implanon would not recommend...,1.0,"May 11, 2016",6,140,0
3,3,184526,Hydroxyzine,anxiety,i recommend taking as prescribed and the bottl...,10.0,"March 19, 2012",124,104,1
4,4,91587,Dalfampridine,multiple sclerosis,i have been on ampyra for days and have been ...,9.0,"August 1, 2010",101,74,1

## Tokenize and Lowercase Text

### Subtask:
Tokenize the words in the 'review' column of `df_train`, `df_test`, and `df_validation`, and convert all tokens to lowercase.

In [29]:
import nltk
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

print("NLTK punkt tokenizer and punkt_tab are ready.")

NLTK punkt tokenizer and punkt_tab are ready.

In [30]:
from nltk.tokenize import word_tokenize

def tokenize_and_lowercase(text):
    if not isinstance(text, str):
        return []
    tokens = word_tokenize(text)
    return [word.lower() for word in tokens]

df_train['review'] = df_train['review'].apply(tokenize_and_lowercase)
df_test['review'] = df_test['review'].apply(tokenize_and_lowercase)
df_validation['review'] = df_validation['review'].apply(tokenize_and_lowercase)

display(df_train.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,89879,Cyclosporine,keratoconjunctivitis sicca,"[i, have, used, restasis, for, about, a, year,...",2.0,"April 20, 2013",69,147,0
1,1,143975,Etonogestrel,birth control,"[my, experience, has, been, somewhat, mixed, i...",7.0,"August 7, 2016",4,136,1
2,2,106473,Implanon,birth control,"[this, is, my, second, implanon, would, not, r...",1.0,"May 11, 2016",6,140,0
3,3,184526,Hydroxyzine,anxiety,"[i, recommend, taking, as, prescribed, and, th...",10.0,"March 19, 2012",124,104,1
4,4,91587,Dalfampridine,multiple sclerosis,"[i, have, been, on, ampyra, for, days, and, ha...",9.0,"August 1, 2010",101,74,1

## Remove Stopwords

### Subtask:
Removing common English stopwords from the tokenized 'review' column in `df_train`, `df_test`, and `df_validation`.

In [31]:
import nltk
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

print("NLTK stopwords corpus is ready.")

NLTK stopwords corpus is ready.

In [32]:
from nltk.corpus import stopwords

# Define a set of English stopwords for efficient lookup
stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    if not isinstance(tokens, list):
        return []
    return [word for word in tokens if word not in stop_words]

df_train['review'] = df_train['review'].apply(remove_stopwords)
df_test['review'] = df_test['review'].apply(remove_stopwords)
df_validation['review'] = df_validation['review'].apply(remove_stopwords)

display(df_train.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,89879,Cyclosporine,keratoconjunctivitis sicca,"[used, restasis, year, seen, almost, progress,...",2.0,"April 20, 2013",69,147,0
1,1,143975,Etonogestrel,birth control,"[experience, somewhat, mixed, using, implanon,...",7.0,"August 7, 2016",4,136,1
2,2,106473,Implanon,birth control,"[second, implanon, would, recommend, allfirst,...",1.0,"May 11, 2016",6,140,0
3,3,184526,Hydroxyzine,anxiety,"[recommend, taking, prescribed, bottle, usuall...",10.0,"March 19, 2012",124,104,1
4,4,91587,Dalfampridine,multiple sclerosis,"[ampyra, days, happy, new, pill, first, days, ...",9.0,"August 1, 2010",101,74,1

## Lemmatize Text

### Subtask:

Lemmatize the words in the 'review' column of `df_train`, `df_test`, and `df_validation`.

In [33]:
import nltk
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

try:
    nltk.data.find('corpora/omw-1.4')
except LookupError:
    nltk.download('omw-1.4')

print("NLTK wordnet and omw-1.4 corpora are ready.")

NLTK wordnet and omw-1.4 corpora are ready.

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [34]:
from nltk.stem import WordNetLemmatizer

# Initialize WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_words(tokens):
    if not isinstance(tokens, list):
        return []
    return [lemmatizer.lemmatize(word) for word in tokens]

df_train['review'] = df_train['review'].apply(lemmatize_words)
df_test['review'] = df_test['review'].apply(lemmatize_words)
df_validation['review'] = df_validation['review'].apply(lemmatize_words)

display(df_train.head())

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length,polarity
0,0,89879,Cyclosporine,keratoconjunctivitis sicca,"[used, restasis, year, seen, almost, progress,...",2.0,"April 20, 2013",69,147,0
1,1,143975,Etonogestrel,birth control,"[experience, somewhat, mixed, using, implanon,...",7.0,"August 7, 2016",4,136,1
2,2,106473,Implanon,birth control,"[second, implanon, would, recommend, allfirst,...",1.0,"May 11, 2016",6,140,0
3,3,184526,Hydroxyzine,anxiety,"[recommend, taking, prescribed, bottle, usuall...",10.0,"March 19, 2012",124,104,1
4,4,91587,Dalfampridine,multiple sclerosis,"[ampyra, day, happy, new, pill, first, day, go...",9.0,"August 1, 2010",101,74,1

## Feature Extraction: TF-IDF Vectorization

### Subtask:
Convert the preprocessed text data in the 'review' column of `df_train`, `df_test`, and `df_validation` into numerical feature vectors using TF-IDF.

In [35]:
# Extract the target variable (polarity) for training, testing, and validation sets
y_train = df_train['polarity']
y_test = df_test['polarity']
y_validation = df_validation['polarity']

print("Target variables y_train, y_test, and y_validation have been created.")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")
print(f"Shape of y_validation: {y_validation.shape}")

Target variables y_train, y_test, and y_validation have been created.
Shape of y_train: (110811,)
Shape of y_test: (46108,)
Shape of y_validation: (27703,)

In [36]:
# Join the list of lemmatized words back into a single string for TF-IDF processing
df_train['review_text'] = df_train['review'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '')
df_test['review_text'] = df_test['review'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '')
df_validation['review_text'] = df_validation['review'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '')

print("Joined lemmatized tokens into strings for TF-IDF.")

Joined lemmatized tokens into strings for TF-IDF.

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Limiting to 5000 features for manageable size

# Fit the vectorizer on the training data and transform it
X_train_tfidf = tfidf_vectorizer.fit_transform(df_train['review_text'])

# Transform the test and validation data using the fitted vectorizer
X_test_tfidf = tfidf_vectorizer.transform(df_test['review_text'])
X_validation_tfidf = tfidf_vectorizer.transform(df_validation['review_text'])

print(f"Shape of X_train_tfidf: {X_train_tfidf.shape}")
print(f"Shape of X_test_tfidf: {X_test_tfidf.shape}")
print(f"Shape of X_validation_tfidf: {X_validation_tfidf.shape}")

print("TF-IDF vectorization complete. The features are stored in X_train_tfidf, X_test_tfidf, and X_validation_tfidf.")

Shape of X_train_tfidf: (110811, 5000)
Shape of X_test_tfidf: (46108, 5000)
Shape of X_validation_tfidf: (27703, 5000)
TF-IDF vectorization complete. The features are stored in X_train_tfidf, X_test_tfidf, and X_validation_tfidf.

## Naive Bayes Model for Sentiment Analysis

### Subtask:
Implement a Naive Bayes model for sentiment analysis using the TF-IDF features. Train the model, make predictions, and evaluate its performance on the test and validation datasets.

In [38]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# Initialize the Naive Bayes classifier (MultinomialNB is suitable for TF-IDF features)
naive_bayes_model = MultinomialNB()

# Train the model
naive_bayes_model.fit(X_train_tfidf, y_train)

print("Naive Bayes model trained successfully.")

Naive Bayes model trained successfully.

In [39]:
# Make predictions on the test set
y_pred_test = naive_bayes_model.predict(X_test_tfidf)

# Evaluate the model on the test set
accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)

print("--- Naive Bayes Model Performance on Test Set ---")
print(f"Accuracy: {accuracy_test:.4f}")
print(f"Precision: {precision_test:.4f}")
print(f"Recall: {recall_test:.4f}")
print(f"F1-Score: {f1_test:.4f}")

# Display classification report for the test set
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred_test))

# Display confusion matrix for the test set
print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_pred_test))

--- Naive Bayes Model Performance on Test Set ---
Accuracy: 0.7791
Precision: 0.7726
Recall: 0.9699
F1-Score: 0.8600

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.83      0.33      0.48     13839
           1       0.77      0.97      0.86     32269

    accuracy                           0.78     46108
   macro avg       0.80      0.65      0.67     46108
weighted avg       0.79      0.78      0.74     46108


Confusion Matrix (Test Set):
[[ 4625  9214]
 [  972 31297]]

In [40]:
# Make predictions on the validation set
y_pred_validation = naive_bayes_model.predict(X_validation_tfidf)

# Evaluate the model on the validation set
accuracy_validation = accuracy_score(y_validation, y_pred_validation)
precision_validation = precision_score(y_validation, y_pred_validation)
recall_validation = recall_score(y_validation, y_pred_validation)
f1_validation = f1_score(y_validation, y_pred_validation)

print("--- Naive Bayes Model Performance on Validation Set ---")
print(f"Accuracy: {accuracy_validation:.4f}")
print(f"Precision: {precision_validation:.4f}")
print(f"Recall: {recall_validation:.4f}")
print(f"F1-Score: {f1_validation:.4f}")

# Display classification report for the validation set
print("\nClassification Report (Validation Set):")
print(classification_report(y_validation, y_pred_validation))

# Display confusion matrix for the validation set
print("\nConfusion Matrix (Validation Set):")
print(confusion_matrix(y_validation, y_pred_validation))

--- Naive Bayes Model Performance on Validation Set ---
Accuracy: 0.7815
Precision: 0.7769
Recall: 0.9684
F1-Score: 0.8621

Classification Report (Validation Set):
              precision    recall  f1-score   support

           0       0.82      0.33      0.47      8159
           1       0.78      0.97      0.86     19544

    accuracy                           0.78     27703
   macro avg       0.80      0.65      0.67     27703
weighted avg       0.79      0.78      0.75     27703


Confusion Matrix (Validation Set):
[[ 2723  5436]
 [  618 18926]]

## Support Vector Machine (SVM) Model for Sentiment Analysis

### Subtask:
Implement an SVM model for sentiment analysis using the TF-IDF features. Train the model, make predictions, and evaluate its performance on the test and validation datasets.

In [41]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# Initialize the LinearSVC classifier (suitable for large datasets and text classification)
svm_model = LinearSVC(random_state=42, dual=False) # dual=False is recommended for n_samples > n_features

# Train the model
svm_model.fit(X_train_tfidf, y_train)

print("SVM model trained successfully.")

SVM model trained successfully.

In [42]:
# Make predictions on the test set
y_pred_test_svm = svm_model.predict(X_test_tfidf)

# Evaluate the SVM model on the test set
accuracy_test_svm = accuracy_score(y_test, y_pred_test_svm)
precision_test_svm = precision_score(y_test, y_pred_test_svm)
recall_test_svm = recall_score(y_test, y_pred_test_svm)
f1_test_svm = f1_score(y_test, y_pred_test_svm)

print("--- SVM Model Performance on Test Set ---")
print(f"Accuracy: {accuracy_test_svm:.4f}")
print(f"Precision: {precision_test_svm:.4f}")
print(f"Recall: {recall_test_svm:.4f}")
print(f"F1-Score: {f1_test_svm:.4f}")

# Display classification report for the test set
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred_test_svm))

# Display confusion matrix for the test set
print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_pred_test_svm))

--- SVM Model Performance on Test Set ---
Accuracy: 0.8339
Precision: 0.8605
Recall: 0.9103
F1-Score: 0.8847

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.76      0.66      0.70     13839
           1       0.86      0.91      0.88     32269

    accuracy                           0.83     46108
   macro avg       0.81      0.78      0.79     46108
weighted avg       0.83      0.83      0.83     46108


Confusion Matrix (Test Set):
[[ 9076  4763]
 [ 2896 29373]]

In [43]:
# Make predictions on the validation set
y_pred_validation_svm = svm_model.predict(X_validation_tfidf)

# Evaluate the SVM model on the validation set
accuracy_validation_svm = accuracy_score(y_validation, y_pred_validation_svm)
precision_validation_svm = precision_score(y_validation, y_pred_validation_svm)
recall_validation_svm = recall_score(y_validation, y_pred_validation_svm)
f1_validation_svm = f1_score(y_validation, y_pred_validation_svm)

print("--- SVM Model Performance on Validation Set ---")
print(f"Accuracy: {accuracy_validation_svm:.4f}")
print(f"Precision: {precision_validation_svm:.4f}")
print(f"Recall: {recall_validation_svm:.4f}")
print(f"F1-Score: {f1_validation_svm:.4f}")

# Display classification report for the validation set
print("\nClassification Report (Validation Set):")
print(classification_report(y_validation, y_pred_validation_svm))

# Display confusion matrix for the validation set
print("\nConfusion Matrix (Validation Set):")
print(confusion_matrix(y_validation, y_pred_validation_svm))

--- SVM Model Performance on Validation Set ---
Accuracy: 0.8299
Precision: 0.8583
Recall: 0.9089
F1-Score: 0.8829

Classification Report (Validation Set):
              precision    recall  f1-score   support

           0       0.75      0.64      0.69      8159
           1       0.86      0.91      0.88     19544

    accuracy                           0.83     27703
   macro avg       0.80      0.77      0.79     27703
weighted avg       0.83      0.83      0.83     27703


Confusion Matrix (Validation Set):
[[ 5226  2933]
 [ 1780 17764]]

## CNN Model for Sentiment Analysis

### Subtask: Data Preparation for CNN

Prepare the preprocessed text data for input into a Convolutional Neural Network (CNN) model. This involves:
1.  **Tokenization and Sequencing:** Convert the lemmatized word lists into numerical sequences.
2.  **Padding Sequences:** Ensure all sequences have a uniform length.
3.  **Define Embedding Parameters:** Determine vocabulary size and embedding dimension.

In [44]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Combine all reviews to fit the tokenizer
all_reviews_for_cnn = [
    review for review_list in df_train['review'] for review in review_list
] + [
    review for review_list in df_test['review'] for review in review_list
] + [
    review for review_list in df_validation['review'] for review in review_list
]

# 1. Fit tokenizer on all reviews to create word-to-index mapping
# Limiting num_words to 5000 (similar to TF-IDF) and adding an OOV token
tokenizer_cnn = Tokenizer(num_words=5000, oov_token="<unk>")
tokenizer_cnn.fit_on_texts(df_train['review'])

# Convert text (lists of words) to sequences of integers
X_train_seq = tokenizer_cnn.texts_to_sequences(df_train['review'])
X_test_seq = tokenizer_cnn.texts_to_sequences(df_test['review'])
X_validation_seq = tokenizer_cnn.texts_to_sequences(df_validation['review'])

print("Reviews converted to numerical sequences.")

Reviews converted to numerical sequences.

In [45]:
# 2. Pad sequences to ensure uniform length

# Determine max sequence length (e.g., 99th percentile of review lengths in training data)
# This helps to capture most review information without excessively long sequences
review_lengths = [len(s) for s in X_train_seq]
max_len = int(np.quantile(review_lengths, 0.99)) + 1 # Add 1 to be safe

# Pad sequences with zeros (post-padding means zeros are added at the end)
X_train_padded = pad_sequences(X_train_seq, maxlen=max_len, padding='post')
X_test_padded = pad_sequences(X_test_seq, maxlen=max_len, padding='post')
X_validation_padded = pad_sequences(X_validation_seq, maxlen=max_len, padding='post')

print(f"Max sequence length determined to be: {max_len}")
print(f"Shape of X_train_padded: {X_train_padded.shape}")
print(f"Shape of X_test_padded: {X_test_padded.shape}")
print(f"Shape of X_validation_padded: {X_validation_padded.shape}")

Max sequence length determined to be: 79
Shape of X_train_padded: (110811, 79)
Shape of X_test_padded: (46108, 79)
Shape of X_validation_padded: (27703, 79)

In [46]:
# 3. Define embedding parameters

vocab_size = 5000
embedding_dim = 100

print(f"Vocabulary size for CNN: {vocab_size}")
print(f"Embedding dimension for CNN: {embedding_dim}")

Vocabulary size for CNN: 5000
Embedding dimension for CNN: 100

### Subtask: Build and Train the CNN Model

Now, let's define the architecture of the CNN model, compile it, and train it using the prepared data.

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout

# Define the CNN model architecture
cnn_model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    Conv1D(filters=128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(), # Extracts the most important features
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid') # Binary classification (positive/negative sentiment)
])

# Compile the model
cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

cnn_model.summary()
print("CNN model defined and compiled successfully.")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_max_pooling1d_1          │ ?                      │             0 │
│ (GlobalMaxPooling1D)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

CNN model defined and compiled successfully.

In [48]:
# Train the CNN model
epochs = 5 # Number of training epochs
batch_size = 32 # Size of the training batches

history = cnn_model.fit(
    X_train_padded, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_validation_padded, y_validation)
)

print("CNN model training complete.")

Epoch 1/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 110s 31ms/step - accuracy: 0.8180 - loss: 0.4081 - val_accuracy: 0.8504 - val_loss: 0.3480
Epoch 2/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 111s 32ms/step - accuracy: 0.8889 - loss: 0.2777 - val_accuracy: 0.8753 - val_loss: 0.3081
Epoch 3/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 109s 31ms/step - accuracy: 0.9410 - loss: 0.1628 - val_accuracy: 0.8894 - val_loss: 0.2967
Epoch 4/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 108s 31ms/step - accuracy: 0.9696 - loss: 0.0868 - val_accuracy: 0.8939 - val_loss: 0.4063
Epoch 5/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 144s 32ms/step - accuracy: 0.9789 - loss: 0.0599 - val_accuracy: 0.8947 - val_loss: 0.4032
CNN model training complete.

### Subtask: Evaluate the CNN Model

Evaluate the performance of the trained CNN model on the test dataset.

In [49]:
from sklearn.metrics import classification_report, confusion_matrix

# Make predictions on the test set
y_pred_proba_cnn = cnn_model.predict(X_test_padded)
y_pred_cnn = (y_pred_proba_cnn > 0.5).astype(int) # Convert probabilities to binary predictions

# Evaluate the model on the test set
print("--- CNN Model Performance on Test Set ---")
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred_cnn))

print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_pred_cnn))

1441/1441 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step
--- CNN Model Performance on Test Set ---

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.83      0.82      0.82     13839
           1       0.92      0.93      0.93     32269

    accuracy                           0.90     46108
   macro avg       0.88      0.87      0.87     46108
weighted avg       0.89      0.90      0.90     46108


Confusion Matrix (Test Set):
[[11302  2537]
 [ 2291 29978]]

## LSTM Model for Sentiment Analysis

### Subtask:
Implement an LSTM model for sentiment analysis using the prepared sequence data. Train the model, make predictions, and evaluate its performance on the test dataset.

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# Define the LSTM model architecture
lstm_model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    LSTM(128), # LSTM layer with 128 units
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid') # Binary classification
])

# Compile the model
lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

lstm_model.summary()
print("LSTM model defined and compiled successfully.")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

LSTM model defined and compiled successfully.

### Subtask: Train the LSTM Model

In [51]:
# Train the LSTM model
epochs = 5 # Number of training epochs
batch_size = 32 # Size of the training batches

history_lstm = lstm_model.fit(
    X_train_padded, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_validation_padded, y_validation)
)

print("LSTM model training complete.")

Epoch 1/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 454s 130ms/step - accuracy: 0.7602 - loss: 0.5100 - val_accuracy: 0.8342 - val_loss: 0.3799
Epoch 2/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 450s 130ms/step - accuracy: 0.8536 - loss: 0.3467 - val_accuracy: 0.8467 - val_loss: 0.3474
Epoch 3/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 453s 131ms/step - accuracy: 0.8807 - loss: 0.2917 - val_accuracy: 0.8571 - val_loss: 0.3347
Epoch 4/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 453s 131ms/step - accuracy: 0.9050 - loss: 0.2433 - val_accuracy: 0.8649 - val_loss: 0.3292
Epoch 5/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 460s 133ms/step - accuracy: 0.9248 - loss: 0.2019 - val_accuracy: 0.8709 - val_loss: 0.3429
LSTM model training complete.

### Subtask: Evaluate the LSTM Model

In [52]:
from sklearn.metrics import classification_report, confusion_matrix

# Make predictions on the test set
y_pred_proba_lstm = lstm_model.predict(X_test_padded)
y_pred_lstm = (y_pred_proba_lstm > 0.5).astype(int) # Convert probabilities to binary predictions

# Evaluate the model on the test set
print("--- LSTM Model Performance on Test Set ---")
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred_lstm))

print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_pred_lstm))

1441/1441 ━━━━━━━━━━━━━━━━━━━━ 56s 39ms/step
--- LSTM Model Performance on Test Set ---

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.79      0.76      0.78     13839
           1       0.90      0.91      0.91     32269

    accuracy                           0.87     46108
   macro avg       0.85      0.84      0.84     46108
weighted avg       0.87      0.87      0.87     46108


Confusion Matrix (Test Set):
[[10523  3316]
 [ 2743 29526]]

## CNN-LSTM Model for Sentiment Analysis

### Subtask:
Implement a CNN-LSTM model for sentiment analysis using the prepared sequence data. Train the model, make predictions, and evaluate its performance on the test dataset.

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, LSTM, Dense, Dropout

# Define the CNN-LSTM model architecture
cnn_lstm_model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    Conv1D(filters=128, kernel_size=5, activation='relu'),
    MaxPooling1D(pool_size=max_len - 5 + 1), # Max pooling over the entire sequence after Conv1D
    LSTM(128), # LSTM layer with 128 units
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid') # Binary classification
])

# Compile the model
cnn_lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

cnn_lstm_model.summary()
print("CNN-LSTM model defined and compiled successfully.")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

CNN-LSTM model defined and compiled successfully.

### Subtask: Train the CNN-LSTM Model

In [54]:
# Train the CNN-LSTM model
epochs = 5 # Number of training epochs
batch_size = 32 # Size of the training batches

history_cnn_lstm = cnn_lstm_model.fit(
    X_train_padded, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_validation_padded, y_validation)
)

print("CNN-LSTM model training complete.")

Epoch 1/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 124s 35ms/step - accuracy: 0.8154 - loss: 0.4099 - val_accuracy: 0.8436 - val_loss: 0.3563
Epoch 2/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 123s 35ms/step - accuracy: 0.8856 - loss: 0.2827 - val_accuracy: 0.8702 - val_loss: 0.3240
Epoch 3/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 139s 35ms/step - accuracy: 0.9357 - loss: 0.1744 - val_accuracy: 0.8864 - val_loss: 0.3201
Epoch 4/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 123s 36ms/step - accuracy: 0.9651 - loss: 0.0996 - val_accuracy: 0.8811 - val_loss: 0.3514
Epoch 5/5
3463/3463 ━━━━━━━━━━━━━━━━━━━━ 139s 35ms/step - accuracy: 0.9777 - loss: 0.0637 - val_accuracy: 0.8924 - val_loss: 0.4867
CNN-LSTM model training complete.

### Subtask: Evaluate the CNN-LSTM Model

In [55]:
from sklearn.metrics import classification_report, confusion_matrix

# Make predictions on the test set
y_pred_proba_cnn_lstm = cnn_lstm_model.predict(X_test_padded)
y_pred_cnn_lstm = (y_pred_proba_cnn_lstm > 0.5).astype(int) # Convert probabilities to binary predictions

# Evaluate the model on the test set
print("-- CNN-LSTM Model Performance on Test Set ---")
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred_cnn_lstm))

print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_pred_cnn_lstm))

1441/1441 ━━━━━━━━━━━━━━━━━━━━ 14s 9ms/step
-- CNN-LSTM Model Performance on Test Set ---

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.84      0.78      0.81     13839
           1       0.91      0.94      0.92     32269

    accuracy                           0.89     46108
   macro avg       0.88      0.86      0.87     46108
weighted avg       0.89      0.89      0.89     46108


Confusion Matrix (Test Set):
[[10827  3012]
 [ 1989 30280]]